kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Build template for the Procurment Concierge app.
    tags: node
  name: '${NAME}-${APP_GROUP}-build'
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}-${APP_GROUP}-${ENV_NAME}'
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${NAME}-${APP_GROUP}-${ENV_NAME}'
      labels:
        app: '${NAME}-${APP_GROUP}'
        app-group: ${APP_GROUP}
        template: ${NAME}-build
    spec:
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
      strategy:
        type: Source
        dockerStrategy:
          dockerFilePath: Dockerfile
          env:
            - name: NODE_ENV
              value: production
          incremental: false
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-${APP_GROUP}-${ENV_NAME}:${OUTPUT_IMAGE_TAG}
parameters:
  - name: NAME
    displayName: Name
    required: true
    value: app
  - name: APP_GROUP
    displayName: Application Group
    required: true
    value: concierge
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    required: true
    value: https://github.com/BCDevExchange/concierge
  - name: GIT_REF
    displayName: Git Reference
    required: true
    value: develop
  - name: ENV_NAME
    displayName: The environment tag, one of dev/test/prod.
    required: true
    value: dev
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
